#spring:
#  application:
#    name:jpa-demo

spring:
  datasource:
    url: jdbc:mysql://0.0.0.0:3306/social-media-database
    username: social-media-user
    password: dummypassword
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: default
    show-sql: true
